# Configuration and security data for the app.
# Copy this file to src/secrets.py and fill it with appropriate values.

import os

# Key for crypting the app session cookie.
# Needs to be unique to a given instance.
# One can be generated by running this script, i.e.
# python src/secrets.py
SERVER_COOKIE_KEY = b'' 

# Youtube data API key for searching and retrieving video data from youtube
# Get one at https://developers.google.com/youtube/v3/getting-started
# Note that the API is subject to quotas
YOUTUBE_DEVELOPER_KEY = '' 

# Restric search to a specific Youtube channel by clicking the checkbox next to the search bar
# The channel ID comes from a url of the form https://www.youtube.com/channel/<channel-id>
YOUTUBE_CHANNEL_ID = '' 
YOUTUBE_CHANNEL_NAME = '' # display name for channel

# Region code and language for searching videos on Youtube
# can be set to None to ignore restriction
YOUTUBE_REGION_CODE = 'AU' 
YOUTUBE_LANGUAGE = 'en'

# Setup Microsoft cognitive services for speech to text at
# https://azure.microsoft.com/en-us/services/cognitive-services/speech-to-text/
# And copy-paste the API key and region identifier here.
MS_COGNITIVE_SERVICES_KEY = '' 
MS_COGNITIVE_SERVICES_REGION = '' 

# Mongodb database name
DB_NAME = 'howtoapp'
DB_URL = 'mongodb://localhost:27018'

EXPORT_PASSWORD = '' # fill with a secure password for exporting database content
LOG_TIMEZONE = 'Australia/Brisbane'

# Host and port where the server listens to.
# Typically 0.0.0.0 and 443
SERVER_NAME = 'localhost' # dns name for access control
HOST = os.environ.get('HOST', 'localhost')
PORT = int(os.environ.get('PORT', 8787))

# SSL keys for setting up HTTPS. You can use https://letsencrypt.org/ to get them.
# For debugging over localhost, you can ssl/generate.sh to make and trust a new SSL certificate
# that will only work on the machine where it is run.
SSL_CRT = 'ssl/localhost.crt'
SSL_KEY = 'ssl/localhost.key'
USE_SSL = True # note that youtube disallow playing some videos without HTTPS

if __name__ == '__main__':
    # Generate server cookie key
    from cryptography import fernet
    import base64
    fernet_key = fernet.Fernet.generate_key()
    secret_key = base64.urlsafe_b64decode(fernet_key)
    print('SERVER_COOKIE_KEY =', secret_key)

